language: java
jdk:
  - oraclejdk11
dist: xenial
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  apt:
    packages:
      - dpkg
  chrome: stable
  install:
    - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver