package com.pameladilly.resources;// Generated by Selenium IDE

import com.pameladilly.crud.Application;
import com.pameladilly.crud.controllers.UserController;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.test.context.ContextConfiguration;

@SpringBootTest(classes = UserController.class)
@ContextConfiguration(classes = Application.class)
public class AddNewUserTest {

  private static WebDriver driver;

  private static ConfigurableApplicationContext context;

  private static ChromeOptions options;


  @BeforeAll
  public static void setUp() {
//    System.setProperty("webdriver.chrome.driver", "/usr/local/share/chromedriver");
//    AddNewUserTest.options = new ChromeOptions();
//    options.addArguments("--headless");
//    options.addArguments("--no-sandbox");
//    options.addArguments("--disable-dev-shm-usage");
    AddNewUserTest.driver = new ChromeDriver();

    AddNewUserTest.context = SpringApplication.run(Application.class);

  }

  @AfterAll
  public static void tearDown() {
    AddNewUserTest.driver.quit();
    SpringApplication.exit(context);

  }

  @Test
  public void addNewUser() {
    AddNewUserTest.driver.get("http://localhost:8080/");
    AddNewUserTest.driver.manage().window().setSize(new Dimension(1344, 696));
    AddNewUserTest.driver.findElement(By.cssSelector(".fas")).click();
    AddNewUserTest.driver.findElement(By.id("name")).click();
    AddNewUserTest.driver.findElement(By.id("name")).sendKeys("Pamela");
    AddNewUserTest.driver.findElement(By.id("email")).sendKeys("pameladilly@hotmail.com");
    AddNewUserTest.driver.findElement(By.cssSelector(".btn")).click();
  }
}
